import type { Metadata } from "next";
import "./globals.css";

import Providers from "@/Providers/Providers";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={`${inter} antialiased`}>
              <Providers>
          {children}
              </Providers>
          </body>
      </html>
  );
}
